#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# List of local libraries



# The search paths for the included middleware
SEARCH_20721B2=../mtb_shared/wiced_btsdk/dev-kit/baselib/20721B2/release-v4.2.1
SEARCH_btsdk-audio=../mtb_shared/wiced_btsdk/dev-kit/libraries/btsdk-audio/release-v4.5.0
SEARCH_btsdk-common=../mtb_shared/wiced_btsdk/dev-kit/libraries/btsdk-common/release-v4.5.0
SEARCH_btsdk-drivers=../mtb_shared/wiced_btsdk/dev-kit/libraries/btsdk-drivers/release-v4.5.0
SEARCH_btsdk-host-apps-bt-ble=../mtb_shared/wiced_btsdk/tools/btsdk-host-apps-bt-ble/release-v4.5.0
SEARCH_btsdk-include=../mtb_shared/wiced_btsdk/dev-kit/btsdk-include/release-v4.5.0
SEARCH_btsdk-ota=../mtb_shared/wiced_btsdk/dev-kit/libraries/btsdk-ota/release-v4.5.1
SEARCH_btsdk-peer-apps-ble=../mtb_shared/wiced_btsdk/tools/btsdk-peer-apps-ble/release-v3.3.0
SEARCH_btsdk-peer-apps-ota=../mtb_shared/wiced_btsdk/tools/btsdk-peer-apps-ota/release-v3.3.0
SEARCH_btsdk-rfcomm=../mtb_shared/wiced_btsdk/dev-kit/libraries/btsdk-rfcomm/release-v4.3.0
SEARCH_btsdk-utils=../mtb_shared/wiced_btsdk/tools/btsdk-utils/release-v4.4.1
SEARCH_TARGET_CYW920721M2EVK-01=../mtb_shared/wiced_btsdk/dev-kit/bsp/TARGET_CYW920721M2EVK-01/release-v4.7.0
SEARCH_btsdk-tools=../mtb_shared/wiced_btsdk/dev-kit/btsdk-tools/release-v3.3.0
SEARCH_core-make=../mtb_shared/core-make/release-v1.9.1

# Search libraries added to build
SEARCH+=$(SEARCH_20721B2)
SEARCH+=$(SEARCH_btsdk-audio)
SEARCH+=$(SEARCH_btsdk-common)
SEARCH+=$(SEARCH_btsdk-drivers)
SEARCH+=$(SEARCH_btsdk-host-apps-bt-ble)
SEARCH+=$(SEARCH_btsdk-include)
SEARCH+=$(SEARCH_btsdk-ota)
SEARCH+=$(SEARCH_btsdk-peer-apps-ble)
SEARCH+=$(SEARCH_btsdk-peer-apps-ota)
SEARCH+=$(SEARCH_btsdk-rfcomm)
SEARCH+=$(SEARCH_btsdk-utils)
SEARCH+=$(SEARCH_TARGET_CYW920721M2EVK-01)
SEARCH+=$(SEARCH_btsdk-tools)
SEARCH+=$(SEARCH_core-make)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_20721B2
COMPONENTS += MW_BTSDK_AUDIO
COMPONENTS += MW_BTSDK_COMMON
COMPONENTS += MW_BTSDK_DRIVERS
COMPONENTS += MW_BTSDK_HOST_APPS_BT_BLE
COMPONENTS += MW_BTSDK_INCLUDE
COMPONENTS += MW_BTSDK_OTA
COMPONENTS += MW_BTSDK_PEER_APPS_BLE
COMPONENTS += MW_BTSDK_PEER_APPS_OTA
COMPONENTS += MW_BTSDK_RFCOMM
COMPONENTS += MW_BTSDK_UTILS
COMPONENTS += MW_TARGET_CYW920721M2EVK_01
COMPONENTS += MW_BTSDK_TOOLS
COMPONENTS += MW_CORE_MAKE
